services:
  ui-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selenide-ui-tests
    environment:
      - MAVEN_OPTS=-Xmx1g
      - RUN_PROFILE=CI
    volumes:
      - ./target:/app/target
